[package]
name = "spargio-protocols"
version = "0.5.8"
edition = "2024"
license = "MIT"
description = "Protocol integration companion crate for spargio (tls/ws/quic)"
repository = "https://github.com/soumyarupsarkar/spargio"

[dependencies]
futures = "0.3"
spargio = { version = "0.5.8", path = "../.." }

[features]
default = []
uring-native = ["spargio/uring-native"]

[dev-dependencies]
