[package]
name = "spargio-ws"
version = "0.4.1"
edition = "2024"
license = "MIT"
description = "WebSocket companion crate for spargio (async-tungstenite bridge)"
repository = "https://github.com/soumyarupsarkar/spargio"

[dependencies]
async-tungstenite = "0.29"
spargio = { version = "0.4.1", path = "../..", features = ["uring-native"] }
spargio-protocols = { version = "0.4.1", path = "../spargio-protocols", features = ["uring-native"] }

[dev-dependencies]
futures = "0.3"
