[package]
name = "spargio-quic"
version = "0.5.0"
edition = "2024"
license = "MIT"
description = "QUIC companion crate for spargio (quinn bridge)"
repository = "https://github.com/soumyarupsarkar/spargio"

[dependencies]
bytes = "1"
quinn = "0.11"
quinn-proto = "0.11"
spargio = { version = "0.5.0", path = "../.." }
tokio = { version = "1", features = ["rt", "rt-multi-thread", "time"] }

[dev-dependencies]
futures = "0.3"
rcgen = "0.13"
rustls = "0.23"
